### ISSUE TITLE
404 for article

### ISSUE THREAD

**Issue by bq1028** [johnbiundo/mvc-sessions#1]
when click [https://github.com/johnbiundo/mvc-sessions/blob/master], show 404 page

**Comment by johnbiundo** [comment]
@bq1028 This seems to work now.  Please comment back if not.  Thank you.

**Comment by bq1028** [comment]
not fix, see below. thank you
![image](https://user-images.githubusercontent.com/36618903/61674220-89df0380-ad25-11e9-8d1c-6ed477bf7c79.png)

**Comment by johnbiundo** [comment]
@bq1028 Thanks again.

But, sorry -- where are you getting that link from?  

The main github repo is here: https://github.com/johnbiundo/mvc-sessions

**Comment by bq1028** [comment]
@johnbiundo, thank you so much first
   yes, i get your repo from the link you point out,  and then scroll screen to Descritpion , when i click link below, show 404 page,

![image](https://user-images.githubusercontent.com/36618903/61686907-911d0600-ad53-11e9-919d-64d2d908bf04.png)
